### PR TITLE
Fixes for Mock chapter

### PR DESCRIPTION
**Pull request by xsuchy**
Several issues I found in a Mock chapter.

### CODE REVIEW

**Comment by voxik** [comment]
Why is there the quote at the beginning? I wanted to fix it, but it would collide with this PR ....

**Comment by xsuchy** [comment]
Because the 3 first paragraphs are quotations.

**Comment by voxik** [comment]
Hmm, that is hardly obvious. But it the paragraph started started as:

> This is what upstream documentation says about Mock: "...."

Or if it was using some "quoting" style, it would be probably easier to understand ...

**Comment by xsuchy** [comment]
Well, I was not adding or changing the quote. I just changed the URL. That URL point to the wiki page, which is abandoned for some time.

**Pull request merged**
